CREATE TABLE IF NOT EXISTS USER_PROFILE(
	UPR_USER_ID NUMBER PRIMARY KEY,
	UPR_USER_NAME VARCHAR(32),
	UPR_USER_PASSWD VARCHAR(64),
	UPR_IS_USER_ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS ROLE(
	ROLE_ID NUMBER PRIMARY KEY,
	ROLE_NAME VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS USER_ROLE(
	USRL_USER_ID NUMBER NOT NULL,
	USRL_ROLE_ID NUMBER NOT NULL,
	FOREIGN KEY (USRL_USER_ID) REFERENCES USER_PROFILE(UPR_USER_ID),
	FOREIGN KEY (USRL_ROLE_ID) REFERENCES ROLE(ROLE_ID)

);
